version: "3"
services: 
    client:
        image: authservice
        restart: always
        ports:
            - "80:3000"
        entrypoint: ["npm", "start"]
        environment: 
            - PORT=3000
            - MONGODB_HOST=mongodb
            - MONGODB_PORT=27017
        links: 
            - mongodb
        networks: 
            - authnetwork
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes: 
            - dbdata:/data/db
        ports:
            - '27017:27017'
        networks: 
            - authnetwork
networks: 
    authnetwork:
        driver: bridge
volumes:
    dbdata:
        